dataset: 'c3vd'
motion: True
meshing:
  eval_rec: True
tracking:
  vis_freq: 30
  vis_inside_freq: 25
  ignore_edge_W: 0
  ignore_edge_H: 0 
  seperate_LR: False
  const_speed_assumption: False
  lr: 0.0001
  pixels: 5000
  iters: 50
mapping:
  every_frame: 1
  vis_freq: 10
  vis_inside_freq: 99 
  mesh_freq: 100
  ckpt_freq: 100 
  keyframe_every: 1
  mapping_window_size: 10
  pixels: 5000
  iters_first: 1500
  iters: 300
  BA_cam_lr: 0.0001


cam:
  H: 1080
  W: 1350
  fx: 802.319
  fy: 801.885
  cx: 668.286
  cy: 547.733
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
#cam:
  #H: 720
  #H: 680
  #W: 960
  #W: 1200
  #fx: 472.64955100886347
  #fx: 590.811938
  #fy: 472.64955100886347
  #fy: 446.3912426
  #cx: 479.5
 # cx: 599.375
  #cy: 359.5
 # cy: 339.5278
  #png_depth_scale: 1 #for depth image in png format
  #crop_edge: 0 